### ISSUE TITLE
Is it possible to make this piano functional on mobile devices?

### ISSUE THREAD

**Issue by lizbanach** [felipefialho/piano#12]
It seems as if the click animation works well, but the note is not played on mobile. Please let me know. Thank you!

**Comment by LFeh** [comment]
Stranged, It was working.

There are any specific node that doesn't work to you?

In my Nexus 5 working perfectly.

**Comment by erbanach** [comment]
I am on an iPhone/Safari/iOS 10 and the animations are working with touch but the sounds are not playing.

**Comment by LFeh** [comment]
Uhmmm, I'll try fix it.

Thanks!

**Comment by erbanach** [comment]
Hi @LFeh - have you had any luck fixing this issue? Let me know!

**Comment by LFeh** [comment]
@erbanach I am trying test on iPhone to know what is the problem.

**Comment by herberthenrique** [comment]
Hi @erbanach, i made some tests on iphone 6/ios10
worked fine on safari and chrome.

are you with the iphone's silent switch on?

**Comment by kadurodrigues** [comment]
It's work fine to me! I'm using iphone 6 with iOS 10 on safari.

**Comment by LFeh** [comment]
Key @erbanach, check if it works now?

**Comment by allanlealluz** [comment]
yeh

**Comment by felipefialho** [comment]
This already works for almost of devices
